---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak

spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8080
  selector:
    app: keycloak